# Generated by Django 4.2 on 2023-04-24 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager_base', '0002_alter_company_options_alter_comment_company_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['date_update'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['role'], 'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
    ]
